site_name: Bryan Kroger DevOps Documentation

theme:
  name: material
  icon:
    logo: material/image-filter-hdr
  # try to imitate woven-planet.global colors
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
  custom_dir: overrides

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Helm:
      Home: helm/index.md
      Testing: helm/testing.md
      Libararies: helm/libraries.md
  - Kubernetes:
      Home: kubernetes/index.md
      Colima: kubernetes/colima.md
      K3s: kubernetes/k3s.md
      k9s: kubernetes/k9s.md
      Kubie: kubernetes/kubie.md
      Opa: kubernetes/opa.md
      'AWS EKS': kubernetes/aws-eks.md
  - Terraform:
      Home: terraform/index.md
      Vault: terraform/vault.md
      Security: terraform/security.md
  - Github:
      Home: github/index.md
  - AWS:
      Home: aws/index.md
  - 'Tips and Tricks':
      Home: tips-and-tricks/index.md
      Helm: tips-and-tricks/helm.md
      Kubernetes: tips-and-tricks/k8s.md
      Aws: tips-and-tricks/aws.md
      JQuery: tips-and-tricks/jq.md


